# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf38a9615193744b46ae73ba907cd7697f866e13f77a3b4cc1b30cab3aab42a864dfad2240759c352a419a651b6b533855eb880b421f33ae1df0f75a28165bd

test:
  secret_key_base: 3bb6280367e6eb6a9ac7e5bf08787fd99c093fe4fb83a4fa14af0e13fb0e4dba030b208a7c891e464debb99c09acd924176bb9b252d5aef5ead868d4efaead52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
